# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-09 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='short_url',
            field=models.URLField(max_length=191, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=191, unique=True),
        ),
    ]
